server:
  port: 8081

spring:
  batch:
    job:
      enabled: false
  cloud:
    config:
      enabled: false
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/mytestjobrepository?useSSL=true
    username: ensocrmadmin
    password: ensocrmadmin
    driver-class-name: com.mysql.cj.jdbc.Driver

  inputrecorddatasource:
    jdbc-url: jdbc:mysql://localhost:3306/mirrorprojectdatastore?useSSL=true
    username: ensocrmadmin
    password: ensocrmadmin
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    default-schema: mirrorprojectdatastore
    change-log: db/changelog/changelog-master.xml
    user: ensocrmadmin
    password: ensocrmadmin

logging:
  level:
    root: INFO
    
msg: testnewww
